### ISSUE TITLE
DeprecationWarning: Unhandled promise rejections are deprecated

### ISSUE THREAD

**Issue by pcuellar** [OfirKP/Whatsapp-Net#2]
Hi, 

I am getting this error when running 'scrape.js'. 
MacOS 10.15.5
node v12.18.0
npm 6.14.4

```
(node:86815) UnhandledPromiseRejectionWarning: Error: Navigation failed because browser has disconnected!
    at CDPSession.<anonymous> (/Users/GitHub/Whatsapp-Net/node_modules/puppeteer/lib/LifecycleWatcher.js:46:107)
    at CDPSession.emit (events.js:315:20)
    at CDPSession._onClosed (/Users/GitHub/Whatsapp-Net/node_modules/puppeteer/lib/Connection.js:215:10)
    at Connection._onClose (/Users/GitHub/Whatsapp-Net/node_modules/puppeteer/lib/Connection.js:138:15)
    at WebSocket.<anonymous> (/Users/GitHub/Whatsapp-Net/node_modules/puppeteer/lib/WebSocketTransport.js:48:22)
    at WebSocket.onClose (/Users/GitHub/Whatsapp-Net/node_modules/ws/lib/event-target.js:124:16)
    at WebSocket.emit (events.js:315:20)
    at WebSocket.emitClose (/Users/GitHub/Whatsapp-Net/node_modules/ws/lib/websocket.js:191:10)
    at Socket.socketOnClose (/Users/GitHub/Whatsapp-Net/node_modules/ws/lib/websocket.js:850:15)
    at Socket.emit (events.js:315:20)
  -- ASYNC --
    at Frame.<anonymous> (/Users/GitHub/Whatsapp-Net/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (/Users/GitHub/Whatsapp-Net/node_modules/puppeteer/lib/Page.js:674:49)
    at Page.<anonymous> (/Users/GitHub/Whatsapp-Net/node_modules/puppeteer/lib/helper.js:112:23)
    at main (/Users/GitHub/Whatsapp-Net/scrape.js:10:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:86815) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:86815) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by OfirKP** [comment]
Hi! I updated some of the code to support newer versions of WhatsApp Web.
Could you please try running the script again and see if the issue was resolved?

Thanks again for contributing,
Ofir

**Comment by pcuellar** [comment]
Just tested it with the same system environment I used before and it works great. 
Great work, thank you so much! 🔥
